version: "3.9"
services:
  modbus-server:
    image: "modbus-server"
    depends_on:
      - mariadb
    restart: "always"
    ports:
      - "0.0.0.0:6651:6651/tcp"
    environment:
      - PARSING_SHOW_VALUE=false
      - DATABASE_USER=user
      - DATABASE_PASSWORD=user_passwd
      - DATABASE_HOSTNAME=mariadb
      - DATABASE_DATABASE_NAME=modbus_rtu
  mariadb:
    image: mariadb:10.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_passwd
      - MYSQL_PASSWORD=user_passwd
      - MYSQL_USER=user
      - MYSQL_DATABASE=modbus_rtu
